# action.yml
name: 'AddRemoveLabel'
description: 'Manage labels on GH pull requests'
inputs:
  GITHUB_TOKEN:
    description: 'GH token'
    required: true
  GITHUB_EVENT_PATH:
    description: 'GH event path'
    required: true
  ACTION:
    description: 'The action perform, can be ether REVIEW_REQUESTED or REVIEWED'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.GITHUB_EVENT_PATH }}
    - ${{ inputs.ACTION }}
